---
title: "Contact"
---

The best way to reach me is by email, which I check far too frequently. I have a phone, but honestly, I don't know the number and I respond faster to email anyway. 

- Email: [dalpiaz2@illinois.edu](mailto:dalpiaz2@illinois.edu)
- Office: Room 36, 703 S. Wright
- Office during COVID: Zoom!

Other place you can find me:

- [GitHub](https://github.com/daviddalpiaz/)
- [Reddit](https://www.reddit.com/user/daviddalpiaz)
- [Statistics @ Illinois Faculty Page](https://stat.illinois.edu/directory/profile/dalpiaz2)

## Schedule

For the **Fall 2020** semester I am teaching asynchronously **online**. This will likely be true for **Spring 2021** as well. As such, I have no set schedule outside of office hours and a few regular meetings.

### Office Hours

Due to health and safety concerns, all **Fall 2020** office hours will be held remotely. For STAT 432 and STAT 510 office hour schedules, please see the relevant [syllabus or course website](teaching.html).

Currently, all office hours are "open" office hours, meaning you can stop by for class questions, or really anything at all, but questions related to courses will be given priority.

If you would like to schedule a non-course related meeting, please send me an email! It would be helpful to suggest two possible times, on two different days. During this global work from home experiment, I have a strong preference for afternoon meetings. Please also indicate a brief agenda for the meeting. If possible, I will try to resolve the issue immediately via email.
