---
title: "Teaching"
---

## University of Illinois 

- **STAT 400:** Statistics and Probability I [[sp-18](https://daviddalpiaz.github.io/stat400sp18/)] [[fa-17](https://daviddalpiaz.github.io/stat400fa17/)]
- **STAT 420:** Statistical Modeling in R [[su-17](https://www.coursera.org/learn/stat-420/)]
    - Taught as part of the Master of [Computer Science](https://cs.illinois.edu/) in Data Science program in collaboration with [Coursera](https://www.coursera.org/degrees/masters-in-computer-data-science). I currently maintain an open-source textbook, [Applied Statistics with R](https://daviddalpiaz.github.io/appliedstats/) for use with the course. Soon to partially be released as public MOOCs on the Coursera platform.
- **STAT 432:** Basics of Statistical Learning [[**fa-20**](http://fall-2020.stat432.org/)] [[sp-20](http://spring-2020.stat432.org/)] [[fa-19](http://fall-2019.stat432.org/)] [[sp-18](https://daviddalpiaz.github.io/stat432sp18/)] [[fa-17](https://daviddalpiaz.github.io/stat430fa17/)]
    - Covers the entirety of [An Introduction to Statistical Learning with Applications in R](http://www-bcf.usc.edu/~gareth/ISL/). I currently maintain an open-source supplemental textbook, [R for Statistical Learning](https://daviddalpiaz.github.io/r4sl/) which focuses on using R to perform statistical learning techniques.
- **STAT 510:** Mathematical Statistics [[**fa-20**](http://math-stat.org/)]

## Ohio State University

- **STAT 3202:** Introduction to Statistical Inference [[sp-19](https://daviddalpiaz.github.io/stat3202-sp19//)] [[fa-18](https://daviddalpiaz.github.io/stat3202-au18/)]
- **STAT 4194:** Data Analytics Capstone [[sp-19](https://daviddalpiaz.github.io/stat4194-sp19/)]

## Textbooks

- [Applied Statistics with R](https://daviddalpiaz.github.io/appliedstats/)
    - Still a work in progress, but the content coverage is more or less solidified. Provides an introduction to both R and regression modeling for students with undergraduate experience in probability and statistics. Currently in use for [STAT 420](https://courses.illinois.edu/schedule/2018/spring/STAT/420) both in-person and online at [UIUC](http://illinois.edu/) for the Departments of [Statistics](http://www.stat.illinois.edu/) and [Computer Science](https://cs.illinois.edu/).
- [R for Statistical Learning](https://daviddalpiaz.github.io/r4sl/)
    - Currently undergoing considerable changes and developments. Originally intended to be supplemental notes to [ISL](http://www-bcf.usc.edu/~gareth/ISL/) in order to provide additional R code and R Markdown examples, the text is starting to become a complete reference text for [STAT 432 - Basics of Statistical Learning](http://stat432.org) at [UIUC](http://illinois.edu/) for the Departments of [Statistics](http://www.stat.illinois.edu/). Target audience is advanced undergraduate students in statistics with previous experience with R and regression. 
