---
title: "Research Opportunities"
output:
  html_document:
    toc: true
---

***

- **Published:** Tuesday, August 18, 2020
- **Updated:** `r format(file.mtime("research-opportunities.Rmd"), "%A, %B %d, %Y")`

***

I often receive emails from students asking: "Do you currently have any research opportunities available?"

- **Short answer:** "No."
- **Long answer:** "The statistics department runs a program called Undergraduate Research Experience in Statistics and I enjoy mentoring students as a part of this program. However, because research is not the main focus of my position, I generally don't have a ton of project ideas at the ready. Read on to learn how we might collaborate!"

## About Me

- my interests
- my anti-interests

## About You

- hopefully UG student
- hopefully a STAT student

## URES

## A Successful Colaboration

- what did charlie do?


## Metadata {-}

- **Published:** Saturday, August 29, 2020
- **Updated:** `r format(file.mtime("template.Rmd"), "%A, %B %d, %Y")`
