---
title: "David Dalpiaz"
---

***

Hello and welcome to my webzone! 

I am currently a [Teaching Assistant Professor](https://stat.illinois.edu/directory/profile/dalpiaz2) for the [Department of Statistics](https://stat.illinois.edu/) at the [University of Illinois at Urbana-Champaign](https://illinois.edu/).

After a BS in [Mathematics](https://math.illinois.edu/) at Illinois, I completed a PhD in Statistics at Illinois with [Ping Ma](http://malab.uga.edu/). I then spent four years as a Visiting Assistant Professor, then Lecturer and MS Academic Advisor for Statistics @ Illinois.

I recently spent a year as an [Associated Assistant Professor](https://stat.osu.edu/people/dalpiaz.14) and [Data Analytics Program Specialist](https://data-analytics.osu.edu/) for the [Department of Statistics](https://stat.osu.edu/) at [**The** Ohio State University](https://www.osu.edu/). Go Bucks? While away from Illinois, I was an [Adjunct Teaching Assistant Professor](https://stat.illinois.edu/directory/profile/dalpiaz2) for Statistics @ Illinois where my course [Statistical Modeling in R](http://stat420.org) is part of the online [Master of Computer Science in Data Science](https://www.coursera.org/degrees/masters-in-computer-data-science). 

But now I have returned to spend even more time at Illinois. Yes, I have spent a lot of time at UIUC. [I’m still mad they don’t use UIUC anymore.](https://en.wikipedia.org/wiki/List_of_the_oldest_currently_registered_Internet_domain_names) Oh well. Go Illini!

## Contact

The best way to reach me is by email, which I check far too frequently. I have a phone, but honestly, I don't know the number and I respond faster to email anyway. 

- Office: Room 36, 703 S. Wright
- Email: [dalpiaz2@illinois.edu](mailto:dalpiaz2@illinois.edu)

You can also find me on [GitHub](https://github.com/daviddalpiaz/) and [Reddit](https://www.reddit.com/user/daviddalpiaz).

## Schedule

For the **Fall 2020** semester I am teaching: Online.

### Office Hours

Due to health and safety concerns, all **Fall 2020** office hours will be held remotely. For STAT 432 and STAT 510 office hour schedules, please see the relevant syllabus. 

If you would like to schedule a non-course related meeting, please send an email suggesting two possible times, on two different days. During this global work from home experiment, I have a strong preference for afternoon meetings. Please also indicate a brief agenda for the meeting. If possible, I will try to resolve the issue immediately via email.

<!-- My **Spring 2020** office hours for STAT 432 can be found in the [STAT 432 syllabus](https://spring-2020.stat432.org/syllabus.html). -->

<!-- Currently, all office hours are "open" office hours, meaning you can stop by for class questions, or really anything at all, but questions about class will be given priority. -->

<!-- If you need to schedule a meeting outside of these times, please send an email suggesting two possible times, on two different days. (A total of four suggested times.) I have a preference for time-slots directly adjacent to current office hours or directly after a class. Please also indicate a brief agenda for the meeting. If possible, I will also try to resolve the issue immediately via email. -->

## Teaching

### University of Illinois 

- **STAT 400:** Statistics and Probability I [[Spring 2018](https://daviddalpiaz.github.io/stat400sp18/)] [[Fall 2017](https://daviddalpiaz.github.io/stat400fa17/)]
- **STAT 420:** Statistical Modeling in R [[Summer 2017](https://www.coursera.org/learn/stat-420/)]
    - Taught as part of the Master of [Computer Science](https://cs.illinois.edu/) in Data Science program in collaboration with [Coursera](https://www.coursera.org/degrees/masters-in-computer-data-science). I currently maintain an open-source textbook, [Applied Statistics with R](https://daviddalpiaz.github.io/appliedstats/) for use with the course. Soon to partially be released as public MOOCs on the Coursera platform.
- **STAT 432:** Basics of Statistical Learning [[**Fall 2020**](http://fall-2020.stat432.org/)] [[Spring 2020](http://spring-2020.stat432.org/)] [[Fall 2019](http://fall-2019.stat432.org/)] [[Spring 2018](https://daviddalpiaz.github.io/stat432sp18/)] [[Fall 2017](https://daviddalpiaz.github.io/stat430fa17/)]
    - Covers the entirety of [An Introduction to Statistical Learning with Applications in R](http://www-bcf.usc.edu/~gareth/ISL/). I currently maintain an open-source supplemental textbook, [R for Statistical Learning](https://daviddalpiaz.github.io/r4sl/) which focuses on using R to perform statistical learning techniques.
- **STAT 510:** Mathematical Statistics [[**Fall 2020**](http://math-stat.org/)]

### Ohio State University

- **STAT 3202:** Introduction to Statistical Inference [[Spring 2019](https://daviddalpiaz.github.io/stat3202-sp19//)] [[Autumn 2018](https://daviddalpiaz.github.io/stat3202-au18/)]
- **STAT 4194:** Data Analytics Capstone [[Spring 2019](https://daviddalpiaz.github.io/stat4194-sp19/)]

## Writing

- [Applied Statistics with R](https://daviddalpiaz.github.io/appliedstats/)
    - Still a work in progress, but the content coverage is more or less solidified. Provides an introduction to both R and regression modeling for students with undergraduate experience in probability and statistics. Currently in use for [STAT 420](https://courses.illinois.edu/schedule/2018/spring/STAT/420) both in-person and online at [UIUC](http://illinois.edu/) for the Departments of [Statistics](http://www.stat.illinois.edu/) and [Computer Science](https://cs.illinois.edu/).
- [R for Statistical Learning](https://daviddalpiaz.github.io/r4sl/)
    - Currently undergoing considerable changes and developments. Originally intended to be supplemental notes to [ISL](http://www-bcf.usc.edu/~gareth/ISL/) in order to provide additional R code and R Markdown examples, the text is starting to become a complete reference text for [STAT 432 - Basics of Statistical Learning](http://stat432.org) at [UIUC](http://illinois.edu/) for the Departments of [Statistics](http://www.stat.illinois.edu/). Target audience is advanced undergraduate students in statistics with previous experience with R and regression. 

### Notebooks

The following are brief write-ups on a variety of (often student focused) topics in an attempt to only type them once. It's a blog, but not a blog.

::: notes

- <span>2020.08.18</span> » [Ten Simple Rules for Success in STAT 432](ten-rules.html)
- <span>2019.11.28</span> » [Letters of Recommendation](letters.html)
- <span>2019.08.22</span> » [The Extended Syllabus](extended-syllabus.html)
<!-- - <span>11 May 2010</span> » [A Quick `dplyr` Tutorial](files/dplyr.html) -->

:::
