---
title: "Schedule | David Dalpiaz"
output:
  html_document:
    lib_dir: libs
    self_contained: no
    theme: cosmo
    css: style.css
    includes:
      in_header: "header.html"
      before_body: "before.html"
---

For the **Spring 2018** semester I will be teaching:

- **STAT 3202:** Tuesday and Thursday, 8:00 AM - 9:20 AM
- **STAT 4194:** Tuesday and Thursday, 12:45 PM - 2:35 PM

Outside of my listed office hours, the best way to reach me is [email](contact.html).

## Office Hours

- **Wednesday:** 10:00 AM - 11:00 AM
- **Thursday:** 5:00 PM - 6:00 PM

Currently, all office hours are "open" office hours, meaning you can stop by for class questions, or really anything at all, but questions about class will be given priority.

If you need to schedule a meeting outside of these times, please send an email suggesting two possible times, on two different days. (A total of four suggested times.) Preference for time-slots directly adjacent to current office hours or directly after a class. Please also indicate a brief agenda for the meeting. If possible, I will also try to resolve the issue immediately via email.
