---
title: "How To Email Your Professor"
author: "[David Dalpiaz](../index.html)"
output:
  html_document:
    css: "../style.css"
---

***

- **Published:** Saturday, August 29, 2020
- **Updated:** Saturday, August 29, 2020

***

Professors get a lot of email. Full disclosure: We don't like reading it. This guide will explain some best practices for effectively communicating with your professors.

**Disclaimer:** This is my opinion. Your other professors will likely have an opinion of their own on this matter. Honestly, that is part of what makes this difficult, but I hope you can take some ideas from this guide.

## A Beautiful Example

```
Subject: [STAT 432] Quiz 02 Missing
From: student-named-bob@illinois.edu
To: dalpiaz2@illinois.edu

Hi Dave,

I saw your announcement, but I don't see Quiz 02 on PrairieLearn. Could you check this?

- Bob
```

There's a chance I would do a victory fist pump if I received this email. This will require some explaining.

First, this is an excellent **subject** line. Right away, I know which course this student is taking. Did you know that professors, especially teaching professor like myself, often teach more than one course in a semester? I also don't need to read the email to understand that the student cannot access the second quiz for the course. Do you hate reading long emails containing paragraph after paragraph? Me too! If you can tell me everything I need to know in the subject line, great! My mind is already wondering how this error could have happened. In this particular instance, I probably can make a reasonable guess: I forgot to grant access. We're off to a great start.

No issue with the **from** line here. Importantly, if you're a student, use your University email. This does a couple things. First, it tells me who you are. I now have a course, and a University identifier. Now, yes I know, your parents likely gave you some wonderful name, but, your name is likely not unique. Your University identifier (NetID at UIUC) is unique. I now know exactly who you are. Also, I know with as much certainty as possible that you are who you say you are. If I get an email from `student-named-bob@gmail.com` that could be literally anyone. Maybe even someone pretending to be Bob phishing for information about Bob. (Hopefully your professor aren't emailing any sensitive information, even through your University email, but better safe than sorry.) So, this email in the from line is good because it uniquely identifies you, and allows for a minor privacy protection.

Next, I love this **greeting**! Why do I love it so much? Because there isn't one. *This is not always appropriate.* Many professor would hate this. But me? If you're in my class, and you nailed the **subject** and **from** address, skip it. I know who you are. (And, in the signoff, you can drop your preferred name, which will add to your identity.) I'll need to expand on this section later.

The **body** of this email is great. It states a fact. Full stop. There's no wavering about.

## Read The Syllabus

Oh wait! Don't skip this step.

- TODO: Piazza

## One Subject, One Email

- just answer the first question

## Wait, Who Cares?

- TODO: because of the lindy effect, you're going to write a lot of emails, not just in school

## Conclusion

Keep it short. Be direct. Mirror expectation



- I saw this on r/professor (yeah, we have a little group_ https://medium.com/@lportwoodstacer/how-to-email-your-professor-without-being-annoying-af-cf64ae0e4087